# Flutter build
variables:
  projectDirectory: s

jobs:
  - job: Android
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: apk
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1